#
# Makefile for all kinds of Fingerprint
#
obj-$(CONFIG_SUNWAVE_FP) += sunwave_fp/
obj-$(CONFIG_FOCALTECH_FINGERPRINT) += focaltech/
obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
