
# If KERNELRELEASE is defined, we've been invoked from the
# kernel build system and can use its language.


obj-$(CONFIG_FOCALTECH_FINGERPRINT)   +=  ff_ctl.o
obj-$(CONFIG_FOCALTECH_FINGERPRINT)	+=  plat-sprd.o




